apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  fsGroup:
    rule: RunAsAny
  allowedCapabilities:
    - NET_RAW
  privileged: true
  allowPrivilegeEscalation: true
  automountServiceAccountToken: true
  runAsUser:
    rule: RunAsAny
  hostPID: true
  hostIPC: true
  hostNetwork: true
  hostPorts:
  - min: 1
    max: 65536

